language: python
python:
  - "2.6"
  - "2.7"
env:
  - USE_MYSQL=1
  - USE_MYSQL=

services:
  - mysql

install:
# Copy libz.so into the virtualenv so that PIL can build PNG support
 - sudo cp /usr/lib/*/libz.so $VIRTUAL_ENV/lib
# command to run tests
script:
 - git clone https://github.com/openhatch/oh-mainline.git
 - cd oh-mainline
 - echo "Most recent commit:"
 - git show | cat
 - echo "OK. Let's see if it works."
 - python manage.py syncdb --migrate --noinput
 - echo 'import django.test.client ; c = django.test.client.Client() ; c.get('/')' | python manage.py shell
# Get development headers for PIL
before_install:
 - if [ -z "$USE_MYSQL" ] ; then deactivate ; else pip install MySQLdb ; fi
 - sudo apt-get update -qq
 - sudo apt-get build-dep -qq python-imaging python-mysqldb
 - sudo apt-get install libjpeg-dev python-mysqldb
 - git config --global user.name TravisDummy
 - git config --global user.email dummy@travis-ci.orgo

before_script:
  - mysql -e 'create database oh_milestone_a'
